### ISSUE TITLE
readingList.csv should start with a comment

### ISSUE THREAD

**Issue by rumca-js** [codemicro/readingList#3]
Hi,
I think that the readingList.csv should start with a comment. The first line is not a real entry. Should be prepended with "#" comment character. Otherwise I have to guess from script which lines should be skipped when importing.

**Comment by codemicro** [comment]
Hey - thanks for opening an issue.

The assertion that that the first line should be commented out is incorrect (plus, there is no standard way for a CSV file to include a comment) - consumers of CSV files should expect that the first line might be a set of column headers.

[Part of the CSV specification](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225/) says, in section 1.1:
> CSV files usually have an additional row at the top called a header row, which gives human-readable names or titles for each of the columns.

I will not be making any changes.

Have a good day :)

**Comment by rumca-js** [comment]
thanks for checking that, sorry for the trouble. have a good day! :-)
